// Auto-generated from jsdmx/src/jsopcode.tbl
// (SpiderMonkey 1.5 modified by Macromedia for Director MX 2004).
//
// Source: E:/Documents/js/javascript15/jsdmx/src/jsopcode.tbl
// Do not edit by hand. Regenerate via tools/gen_js_opcodes.py.

use num_derive::FromPrimitive;

#[derive(Debug, Clone, Copy, PartialEq, Eq, FromPrimitive)]
#[repr(u8)]
pub enum JsOp {
    Nop = 0,
    Push = 1,
    Popv = 2,
    Enterwith = 3,
    Leavewith = 4,
    Return = 5,
    Goto = 6,
    Ifeq = 7,
    Ifne = 8,
    Arguments = 9,
    Forarg = 10,
    Forvar = 11,
    Dup = 12,
    Dup2 = 13,
    Setconst = 14,
    Bitor = 15,
    Bitxor = 16,
    Bitand = 17,
    Eq = 18,
    Ne = 19,
    Lt = 20,
    Le = 21,
    Gt = 22,
    Ge = 23,
    Lsh = 24,
    Rsh = 25,
    Ursh = 26,
    Add = 27,
    Sub = 28,
    Mul = 29,
    Div = 30,
    Mod = 31,
    Not = 32,
    Bitnot = 33,
    Neg = 34,
    New = 35,
    Delname = 36,
    Delprop = 37,
    Delelem = 38,
    Typeof = 39,
    Void = 40,
    Incname = 41,
    Incprop = 42,
    Incelem = 43,
    Decname = 44,
    Decprop = 45,
    Decelem = 46,
    Nameinc = 47,
    Propinc = 48,
    Eleminc = 49,
    Namedec = 50,
    Propdec = 51,
    Elemdec = 52,
    Getprop = 53,
    Setprop = 54,
    Getelem = 55,
    Setelem = 56,
    Pushobj = 57,
    Call = 58,
    Name = 59,
    Number = 60,
    String = 61,
    Zero = 62,
    One = 63,
    Null = 64,
    This = 65,
    False = 66,
    True = 67,
    Or = 68,
    And = 69,
    Tableswitch = 70,
    Lookupswitch = 71,
    NewEq = 72,
    NewNe = 73,
    Closure = 74,
    Exportall = 75,
    Exportname = 76,
    Importall = 77,
    Importprop = 78,
    Importelem = 79,
    Object = 80,
    Pop = 81,
    Pos = 82,
    Trap = 83,
    Getarg = 84,
    Setarg = 85,
    Getvar = 86,
    Setvar = 87,
    Uint16 = 88,
    Newinit = 89,
    Endinit = 90,
    Initprop = 91,
    Initelem = 92,
    Defsharp = 93,
    Usesharp = 94,
    Incarg = 95,
    Incvar = 96,
    Decarg = 97,
    Decvar = 98,
    Arginc = 99,
    Varinc = 100,
    Argdec = 101,
    Vardec = 102,
    Toobject = 103,
    Forname = 104,
    Forprop = 105,
    Forelem = 106,
    Pop2 = 107,
    Bindname = 108,
    Setname = 109,
    Throw = 110,
    In = 111,
    Instanceof = 112,
    Debugger = 113,
    Gosub = 114,
    Retsub = 115,
    Exception = 116,
    Setsp = 117,
    Condswitch = 118,
    Case = 119,
    Default = 120,
    Eval = 121,
    Enumelem = 122,
    Getter = 123,
    Setter = 124,
    Deffun = 125,
    Defconst = 126,
    Defvar = 127,
    Anonfunobj = 128,
    Namedfunobj = 129,
    Initcatchvar = 130,
    Group = 131,
    Setcall = 132,
    Try = 133,
    Finally = 134,
    Swap = 135,
    Argsub = 136,
    Argcnt = 137,
    Deflocalfun = 138,
    Gotox = 139,
    Ifeqx = 140,
    Ifnex = 141,
    Orx = 142,
    Andx = 143,
    Gosubx = 144,
    Casex = 145,
    Defaultx = 146,
    Tableswitchx = 147,
    Lookupswitchx = 148,
    Backpatch = 149,
    BackpatchPop = 150,
    BackpatchPush = 151,
    Setrval = 152,
    Retrval = 153,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum JsOpFormat {
    Byte, Uint16, Const, Jump, Local, Qarg, Qvar, Tableswitch, Lookupswitch, Object,
}

#[derive(Debug, Clone, Copy)]
pub struct JsOpInfo {
    pub op: JsOp,
    pub mnemonic: &'static str,
    /// Fixed instruction length, or -1 if variable (table/lookup switch).
    pub length: i8,
    /// Stack operands consumed; -1 if variable (CALL/NEW).
    pub uses: i8,
    /// Stack operands defined.
    pub defs: i8,
    pub format: JsOpFormat,
}

pub const JS_OP_INFO: &[JsOpInfo] = &[
    JsOpInfo { op: JsOp::Nop, mnemonic: "nop", length: 1, uses: 0, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Push, mnemonic: "push", length: 1, uses: 0, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Popv, mnemonic: "popv", length: 1, uses: 1, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Enterwith, mnemonic: "enterwith", length: 1, uses: 1, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Leavewith, mnemonic: "leavewith", length: 1, uses: 1, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Return, mnemonic: "return", length: 1, uses: 1, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Goto, mnemonic: "goto", length: 3, uses: 0, defs: 0, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::Ifeq, mnemonic: "ifeq", length: 3, uses: 1, defs: 0, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::Ifne, mnemonic: "ifne", length: 3, uses: 1, defs: 0, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::Arguments, mnemonic: "js_arguments_str", length: 1, uses: 0, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Forarg, mnemonic: "forarg", length: 3, uses: 0, defs: 1, format: JsOpFormat::Qarg },
    JsOpInfo { op: JsOp::Forvar, mnemonic: "forvar", length: 3, uses: 0, defs: 1, format: JsOpFormat::Qvar },
    JsOpInfo { op: JsOp::Dup, mnemonic: "dup", length: 1, uses: 1, defs: 2, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Dup2, mnemonic: "dup2", length: 1, uses: 2, defs: 4, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Setconst, mnemonic: "setconst", length: 3, uses: 1, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Bitor, mnemonic: "bitor", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Bitxor, mnemonic: "bitxor", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Bitand, mnemonic: "bitand", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Eq, mnemonic: "eq", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Ne, mnemonic: "ne", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Lt, mnemonic: "lt", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Le, mnemonic: "le", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Gt, mnemonic: "gt", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Ge, mnemonic: "ge", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Lsh, mnemonic: "lsh", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Rsh, mnemonic: "rsh", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Ursh, mnemonic: "ursh", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Add, mnemonic: "add", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Sub, mnemonic: "sub", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Mul, mnemonic: "mul", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Div, mnemonic: "div", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Mod, mnemonic: "mod", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Not, mnemonic: "not", length: 1, uses: 1, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Bitnot, mnemonic: "bitnot", length: 1, uses: 1, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Neg, mnemonic: "neg", length: 1, uses: 1, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::New, mnemonic: "js_new_str", length: 3, uses: -1, defs: 1, format: JsOpFormat::Uint16 },
    JsOpInfo { op: JsOp::Delname, mnemonic: "delname", length: 3, uses: 0, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Delprop, mnemonic: "delprop", length: 3, uses: 1, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Delelem, mnemonic: "delelem", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Typeof, mnemonic: "js_typeof_str", length: 1, uses: 1, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Void, mnemonic: "js_void_str", length: 1, uses: 1, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Incname, mnemonic: "incname", length: 3, uses: 0, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Incprop, mnemonic: "incprop", length: 3, uses: 1, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Incelem, mnemonic: "incelem", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Decname, mnemonic: "decname", length: 3, uses: 0, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Decprop, mnemonic: "decprop", length: 3, uses: 1, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Decelem, mnemonic: "decelem", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Nameinc, mnemonic: "nameinc", length: 3, uses: 0, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Propinc, mnemonic: "propinc", length: 3, uses: 1, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Eleminc, mnemonic: "eleminc", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Namedec, mnemonic: "namedec", length: 3, uses: 0, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Propdec, mnemonic: "propdec", length: 3, uses: 1, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Elemdec, mnemonic: "elemdec", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Getprop, mnemonic: "getprop", length: 3, uses: 1, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Setprop, mnemonic: "setprop", length: 3, uses: 2, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Getelem, mnemonic: "getelem", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Setelem, mnemonic: "setelem", length: 1, uses: 3, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Pushobj, mnemonic: "pushobj", length: 1, uses: 0, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Call, mnemonic: "call", length: 3, uses: -1, defs: 1, format: JsOpFormat::Uint16 },
    JsOpInfo { op: JsOp::Name, mnemonic: "name", length: 3, uses: 0, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Number, mnemonic: "number", length: 3, uses: 0, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::String, mnemonic: "string", length: 3, uses: 0, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Zero, mnemonic: "zero", length: 1, uses: 0, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::One, mnemonic: "one", length: 1, uses: 0, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Null, mnemonic: "js_null_str", length: 1, uses: 0, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::This, mnemonic: "js_this_str", length: 1, uses: 0, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::False, mnemonic: "js_false_str", length: 1, uses: 0, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::True, mnemonic: "js_true_str", length: 1, uses: 0, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Or, mnemonic: "or", length: 3, uses: 1, defs: 0, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::And, mnemonic: "and", length: 3, uses: 1, defs: 0, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::Tableswitch, mnemonic: "tableswitch", length: -1, uses: 1, defs: 0, format: JsOpFormat::Tableswitch },
    JsOpInfo { op: JsOp::Lookupswitch, mnemonic: "lookupswitch", length: -1, uses: 1, defs: 0, format: JsOpFormat::Lookupswitch },
    JsOpInfo { op: JsOp::NewEq, mnemonic: "eq", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::NewNe, mnemonic: "ne", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Closure, mnemonic: "closure", length: 3, uses: 0, defs: 0, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Exportall, mnemonic: "exportall", length: 1, uses: 0, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Exportname, mnemonic: "exportname", length: 3, uses: 0, defs: 0, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Importall, mnemonic: "importall", length: 1, uses: 1, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Importprop, mnemonic: "importprop", length: 3, uses: 1, defs: 0, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Importelem, mnemonic: "importelem", length: 1, uses: 2, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Object, mnemonic: "object", length: 3, uses: 0, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Pop, mnemonic: "pop", length: 1, uses: 1, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Pos, mnemonic: "pos", length: 1, uses: 1, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Trap, mnemonic: "trap", length: 1, uses: 0, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Getarg, mnemonic: "getarg", length: 3, uses: 0, defs: 1, format: JsOpFormat::Qarg },
    JsOpInfo { op: JsOp::Setarg, mnemonic: "setarg", length: 3, uses: 1, defs: 1, format: JsOpFormat::Qarg },
    JsOpInfo { op: JsOp::Getvar, mnemonic: "getvar", length: 3, uses: 0, defs: 1, format: JsOpFormat::Qvar },
    JsOpInfo { op: JsOp::Setvar, mnemonic: "setvar", length: 3, uses: 1, defs: 1, format: JsOpFormat::Qvar },
    JsOpInfo { op: JsOp::Uint16, mnemonic: "uint16", length: 3, uses: 0, defs: 1, format: JsOpFormat::Uint16 },
    JsOpInfo { op: JsOp::Newinit, mnemonic: "newinit", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Endinit, mnemonic: "endinit", length: 1, uses: 0, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Initprop, mnemonic: "initprop", length: 3, uses: 1, defs: 0, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Initelem, mnemonic: "initelem", length: 1, uses: 2, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Defsharp, mnemonic: "defsharp", length: 3, uses: 0, defs: 0, format: JsOpFormat::Uint16 },
    JsOpInfo { op: JsOp::Usesharp, mnemonic: "usesharp", length: 3, uses: 0, defs: 1, format: JsOpFormat::Uint16 },
    JsOpInfo { op: JsOp::Incarg, mnemonic: "incarg", length: 3, uses: 0, defs: 1, format: JsOpFormat::Qarg },
    JsOpInfo { op: JsOp::Incvar, mnemonic: "incvar", length: 3, uses: 0, defs: 1, format: JsOpFormat::Qvar },
    JsOpInfo { op: JsOp::Decarg, mnemonic: "decarg", length: 3, uses: 0, defs: 1, format: JsOpFormat::Qarg },
    JsOpInfo { op: JsOp::Decvar, mnemonic: "decvar", length: 3, uses: 0, defs: 1, format: JsOpFormat::Qvar },
    JsOpInfo { op: JsOp::Arginc, mnemonic: "arginc", length: 3, uses: 0, defs: 1, format: JsOpFormat::Qarg },
    JsOpInfo { op: JsOp::Varinc, mnemonic: "varinc", length: 3, uses: 0, defs: 1, format: JsOpFormat::Qvar },
    JsOpInfo { op: JsOp::Argdec, mnemonic: "argdec", length: 3, uses: 0, defs: 1, format: JsOpFormat::Qarg },
    JsOpInfo { op: JsOp::Vardec, mnemonic: "vardec", length: 3, uses: 0, defs: 1, format: JsOpFormat::Qvar },
    JsOpInfo { op: JsOp::Toobject, mnemonic: "toobject", length: 1, uses: 1, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Forname, mnemonic: "forname", length: 3, uses: 0, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Forprop, mnemonic: "forprop", length: 3, uses: 1, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Forelem, mnemonic: "forelem", length: 1, uses: 2, defs: 4, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Pop2, mnemonic: "pop2", length: 1, uses: 2, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Bindname, mnemonic: "bindname", length: 3, uses: 0, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Setname, mnemonic: "setname", length: 3, uses: 2, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Throw, mnemonic: "throw", length: 1, uses: 1, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::In, mnemonic: "js_in_str", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Instanceof, mnemonic: "js_instanceof_str", length: 1, uses: 2, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Debugger, mnemonic: "debugger", length: 1, uses: 0, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Gosub, mnemonic: "gosub", length: 3, uses: 0, defs: 1, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::Retsub, mnemonic: "retsub", length: 1, uses: 1, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Exception, mnemonic: "exception", length: 1, uses: 0, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Setsp, mnemonic: "setsp", length: 3, uses: 0, defs: 0, format: JsOpFormat::Uint16 },
    JsOpInfo { op: JsOp::Condswitch, mnemonic: "condswitch", length: 1, uses: 0, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Case, mnemonic: "case", length: 3, uses: 1, defs: 0, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::Default, mnemonic: "default", length: 3, uses: 1, defs: 0, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::Eval, mnemonic: "eval", length: 3, uses: -1, defs: 1, format: JsOpFormat::Uint16 },
    JsOpInfo { op: JsOp::Enumelem, mnemonic: "enumelem", length: 1, uses: 3, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Getter, mnemonic: "js_getter_str", length: 1, uses: 0, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Setter, mnemonic: "js_setter_str", length: 1, uses: 0, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Deffun, mnemonic: "deffun", length: 3, uses: 0, defs: 0, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Defconst, mnemonic: "defconst", length: 3, uses: 0, defs: 0, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Defvar, mnemonic: "defvar", length: 3, uses: 0, defs: 0, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Anonfunobj, mnemonic: "anonfunobj", length: 3, uses: 0, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Namedfunobj, mnemonic: "namedfunobj", length: 3, uses: 0, defs: 1, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Initcatchvar, mnemonic: "initcatchvar", length: 3, uses: 1, defs: 0, format: JsOpFormat::Const },
    JsOpInfo { op: JsOp::Group, mnemonic: "group", length: 1, uses: 0, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Setcall, mnemonic: "setcall", length: 3, uses: -1, defs: 2, format: JsOpFormat::Uint16 },
    JsOpInfo { op: JsOp::Try, mnemonic: "try", length: 1, uses: 0, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Finally, mnemonic: "finally", length: 1, uses: 0, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Swap, mnemonic: "swap", length: 1, uses: 2, defs: 2, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Argsub, mnemonic: "argsub", length: 3, uses: 0, defs: 1, format: JsOpFormat::Qarg },
    JsOpInfo { op: JsOp::Argcnt, mnemonic: "argcnt", length: 1, uses: 0, defs: 1, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Deflocalfun, mnemonic: "deflocalfun", length: 5, uses: 0, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Gotox, mnemonic: "gotox", length: 5, uses: 0, defs: 0, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::Ifeqx, mnemonic: "ifeqx", length: 5, uses: 1, defs: 0, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::Ifnex, mnemonic: "ifnex", length: 5, uses: 1, defs: 0, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::Orx, mnemonic: "orx", length: 5, uses: 1, defs: 0, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::Andx, mnemonic: "andx", length: 5, uses: 1, defs: 0, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::Gosubx, mnemonic: "gosubx", length: 5, uses: 0, defs: 1, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::Casex, mnemonic: "casex", length: 5, uses: 1, defs: 0, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::Defaultx, mnemonic: "defaultx", length: 5, uses: 1, defs: 0, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::Tableswitchx, mnemonic: "tableswitchx", length: -1, uses: 1, defs: 0, format: JsOpFormat::Tableswitch },
    JsOpInfo { op: JsOp::Lookupswitchx, mnemonic: "lookupswitchx", length: -1, uses: 1, defs: 0, format: JsOpFormat::Lookupswitch },
    JsOpInfo { op: JsOp::Backpatch, mnemonic: "backpatch", length: 3, uses: 0, defs: 0, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::BackpatchPop, mnemonic: "backpatch_pop", length: 3, uses: 1, defs: 0, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::BackpatchPush, mnemonic: "backpatch_push", length: 3, uses: 0, defs: 1, format: JsOpFormat::Jump },
    JsOpInfo { op: JsOp::Setrval, mnemonic: "setrval", length: 1, uses: 1, defs: 0, format: JsOpFormat::Byte },
    JsOpInfo { op: JsOp::Retrval, mnemonic: "retrval", length: 1, uses: 0, defs: 0, format: JsOpFormat::Byte },
];

impl JsOp {
    pub fn info(self) -> &'static JsOpInfo { &JS_OP_INFO[self as usize] }
    pub fn from_byte(b: u8) -> Option<Self> { num::FromPrimitive::from_u8(b) }
}
