#!/usr/bin/env bash
# Build a diff grid image from snapshot diff PNGs and output a markdown comment.
# Usage: build-diff-grid.sh <snapshots-base> <output-dir>
#   snapshots-base: e.g. vm-rust/tests/snapshots
#   output-dir:     where to write diff-grid.png and comment.md
set -euo pipefail

SNAPSHOTS_BASE="${1:?Usage: build-diff-grid.sh <snapshots-base> <output-dir>}"
OUTPUT_DIR="${2:?Usage: build-diff-grid.sh <snapshots-base> <output-dir>}"
DIFF_DIR="$SNAPSHOTS_BASE/diff"

mkdir -p "$OUTPUT_DIR"

# Collect all diff PNGs
DIFF_FILES=()
while IFS= read -r -d '' f; do
  DIFF_FILES+=("$f")
done < <(find "$DIFF_DIR" -name '*.png' -print0 2>/dev/null | sort -z)

if [ ${#DIFF_FILES[@]} -eq 0 ]; then
  echo "No snapshot diffs found."
  exit 0
fi

echo "Found ${#DIFF_FILES[@]} diff image(s)"

# Build diff-grid: label each image with its relative path, tile in a grid
MONTAGE_ARGS=()
for f in "${DIFF_FILES[@]}"; do
  REL="${f#$DIFF_DIR/}"
  MONTAGE_ARGS+=(-label "$REL" "$f")
done

# Use ImageMagick montage if available
if command -v montage &>/dev/null; then
  # Try with labels; if that fails (e.g. no fonts), retry without.
  # montage may exit nonzero due to font warnings even when it produces output.
  montage "${MONTAGE_ARGS[@]}" \
    -tile 3x -geometry 320x240+4+4 \
    -background '#1a1a1a' -fill '#eee' -pointsize 12 \
    "$OUTPUT_DIR/diff-grid.png" 2>/dev/null \
  || montage "${DIFF_FILES[@]}" \
    -tile 3x -geometry 320x240+4+4 \
    -background '#1a1a1a' \
    "$OUTPUT_DIR/diff-grid.png" 2>/dev/null \
  || true

  # Verify the diff-grid was actually created
  if [ ! -f "$OUTPUT_DIR/diff-grid.png" ]; then
    echo "Warning: montage failed to produce diff-grid"
  fi
  echo "Mosaic written to $OUTPUT_DIR/diff-grid.png"
else
  echo "Warning: ImageMagick montage not found, skipping diff-grid generation"
  # Fall back: just copy individual diffs
  for f in "${DIFF_FILES[@]}"; do
    REL="${f#$DIFF_DIR/}"
    DEST="$OUTPUT_DIR/diffs/$REL"
    mkdir -p "$(dirname "$DEST")"
    cp "$f" "$DEST"
  done
fi

# Build markdown comment body
COMMENT="$OUTPUT_DIR/comment.md"
cat > "$COMMENT" <<'HEADER'
### Snapshot Diff Report

The following snapshots differ from the reference images. Red pixels indicate changes.

HEADER

if [ -f "$OUTPUT_DIR/diff-grid.png" ]; then
  echo '![Snapshot diffs](diff-grid.png)' >> "$COMMENT"
  echo '' >> "$COMMENT"
fi

echo '| Snapshot | Diff |' >> "$COMMENT"
echo '|----------|------|' >> "$COMMENT"
for f in "${DIFF_FILES[@]}"; do
  REL="${f#$DIFF_DIR/}"
  echo "| \`$REL\` | changed |" >> "$COMMENT"
done

echo "" >> "$COMMENT"
echo "Generated by CI — $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$COMMENT"

echo "Comment written to $COMMENT"
