#!/usr/bin/env bash
# Build a snapshot test report with an optional diff grid image.
# Usage: build-diff-grid.sh <snapshots-base> <output-dir>
#   snapshots-base: e.g. vm-rust/tests/snapshots
#   output-dir:     where to write diff-grid.png and comment.md
set -euo pipefail

SNAPSHOTS_BASE="${1:?Usage: build-diff-grid.sh <snapshots-base> <output-dir>}"
OUTPUT_DIR="${2:?Usage: build-diff-grid.sh <snapshots-base> <output-dir>}"
DIFF_DIR="$SNAPSHOTS_BASE/diff"
OUTPUT_SNAPSHOT_DIR="$SNAPSHOTS_BASE/output"

mkdir -p "$OUTPUT_DIR"

# Count total output snapshots
TOTAL_SNAPSHOTS=0
if [ -d "$OUTPUT_SNAPSHOT_DIR" ]; then
  TOTAL_SNAPSHOTS=$(find "$OUTPUT_SNAPSHOT_DIR" -name '*.png' 2>/dev/null | wc -l | tr -d ' ')
fi

# Collect all diff PNGs
DIFF_FILES=()
while IFS= read -r -d '' f; do
  DIFF_FILES+=("$f")
done < <(find "$DIFF_DIR" -name '*.png' -print0 2>/dev/null | sort -z)

DIFF_COUNT=${#DIFF_FILES[@]}
PASS_COUNT=$((TOTAL_SNAPSHOTS - DIFF_COUNT))

echo "Snapshots: $TOTAL_SNAPSHOTS total, $DIFF_COUNT changed, $PASS_COUNT unchanged"

# Build diff grid image if there are diffs
if [ $DIFF_COUNT -gt 0 ]; then
  # Label each image with its relative path
  MONTAGE_ARGS=()
  for f in "${DIFF_FILES[@]}"; do
    REL="${f#$DIFF_DIR/}"
    MONTAGE_ARGS+=(-label "$REL" "$f")
  done

  if command -v montage &>/dev/null; then
    # Try with labels; if that fails (e.g. no fonts), retry without.
    # montage may exit nonzero due to font warnings even when it produces output.
    if ! montage "${MONTAGE_ARGS[@]}" \
      -tile 3x -geometry 320x240+4+4 \
      -background '#1a1a1a' -fill '#eee' -pointsize 12 \
      "$OUTPUT_DIR/diff-grid.png" 2>/dev/null; then
      montage "${DIFF_FILES[@]}" \
        -tile 3x -geometry 320x240+4+4 \
        -background '#1a1a1a' \
        "$OUTPUT_DIR/diff-grid.png" 2>/dev/null \
      || true
    fi

    if [ -f "$OUTPUT_DIR/diff-grid.png" ]; then
      echo "Diff grid written to $OUTPUT_DIR/diff-grid.png"
    else
      echo "Warning: montage failed to produce diff grid"
    fi
  else
    echo "Warning: ImageMagick not found, skipping diff grid"
    for f in "${DIFF_FILES[@]}"; do
      REL="${f#$DIFF_DIR/}"
      DEST="$OUTPUT_DIR/diffs/$REL"
      mkdir -p "$(dirname "$DEST")"
      cp "$f" "$DEST"
    done
  fi
fi

# Build markdown comment body (always generated)
COMMENT="$OUTPUT_DIR/comment.md"

if [ $DIFF_COUNT -eq 0 ]; then
  cat > "$COMMENT" <<EOF
### Snapshot Test Report

All **$TOTAL_SNAPSHOTS** snapshots match the reference images.

Generated by CI — $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF
else
  cat > "$COMMENT" <<EOF
### Snapshot Test Report

**$DIFF_COUNT** of **$TOTAL_SNAPSHOTS** snapshots differ from reference. Red pixels indicate changes.

EOF

  if [ -f "$OUTPUT_DIR/diff-grid.png" ]; then
    echo '![Snapshot diffs](diff-grid.png)' >> "$COMMENT"
    echo '' >> "$COMMENT"
  fi

  echo '| Snapshot | Status |' >> "$COMMENT"
  echo '|----------|--------|' >> "$COMMENT"
  for f in "${DIFF_FILES[@]}"; do
    REL="${f#$DIFF_DIR/}"
    echo "| \`$REL\` | changed |" >> "$COMMENT"
  done

  echo "" >> "$COMMENT"
  echo "Generated by CI — $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$COMMENT"
fi

echo "Comment written to $COMMENT"
