// SPDX-License-Identifier: GPL-3.0-only
//
//! ExampleXtra — reference plugin showing how to author a dirplayer-rs Xtra.
//!
//! Plugin authors write the three impls below. Everything else — the C-ABI
//! exports, the instance registry, the dispatch glue — is generated by
//! `export_plugin!`.
//!
//! Uses `std` for the default allocator. Plugin authors who care about
//! the ~40 KB size saving can switch to `#![no_std]` + `extern crate alloc;`
//! and supply a small allocator (e.g. `talc`, `dlmalloc`) themselves —
//! the SDK itself is `no_std`-compatible.

use xtra_sdk::plugin::{XtraInstance, XtraPlugin, XtraResult};
use xtra_sdk::{Datum, host_env};

// ── User-facing plugin definition ────────────────────────────────────────

pub struct ExamplePlugin;

pub struct ExampleInstance {
    /// Counts how many times `count()` has been called on this instance.
    counter: i32,
}

impl XtraPlugin for ExamplePlugin {
    type Instance = ExampleInstance;

    fn xtra_name() -> &'static str {
        "ExampleXtra"
    }

    fn create_instance(_args: &[Datum]) -> XtraResult<ExampleInstance> {
        host_env::log("ExampleXtra: create_instance");
        Ok(ExampleInstance { counter: 0 })
    }

    fn has_static_handler(name: &str) -> bool {
        matches!(name, "version" | "echo")
    }

    fn call_static_handler(name: &str, args: &[Datum]) -> XtraResult<Datum> {
        match name {
            "version" => Ok(Datum::String("ExampleXtra 1.0".into())),
            "echo" => Ok(args.first().cloned().unwrap_or(Datum::Void)),
            other => Err(format!("ExampleXtra: unknown static handler {}", other)),
        }
    }
}

impl XtraInstance for ExampleInstance {
    fn call_handler(&mut self, name: &str, args: &[Datum]) -> XtraResult<Datum> {
        match name {
            "greet" => {
                let who = args.first().and_then(|d| d.as_str()).unwrap_or("world");
                Ok(Datum::String(format!("Hello, {}", who)))
            }
            "count" => {
                self.counter = self.counter.wrapping_add(1);
                Ok(Datum::Int(self.counter))
            }
            other => Err(format!("ExampleXtra: unknown handler {}", other)),
        }
    }

    fn destroy(&mut self) {
        host_env::log("ExampleXtra: destroy_instance");
    }
}

// One line replaces ~50 lines of C-ABI boilerplate. Emits the instance
// registry, `__plugin_alloc` / `__plugin_dealloc`, and all eight
// `__xtra_*` exports for the WIT contract.
//
// Macro path is `xtra_sdk::export_plugin!` but a bare `export_plugin!`
// also works after the `use xtra_sdk::...` above brings it into scope
// via the macro-use semantics applied by `#[macro_export]`.
xtra_sdk::export_plugin!(ExamplePlugin);
