// W3D IFX block type constants (44 types)

pub const IFX_HEADER: u32         = 0x00584649; // "IFX\0"
pub const CONTEXT_SEP: u32       = 0xFFFFFF01; // -255
pub const FILE_HEADER: u32       = 0xFFFFFF02; // -254
pub const MATERIAL_V1: u32       = 0xFFFFFF10; // -240
pub const MATERIAL: u32          = 0xFFFFFF11; // -239
pub const TEXTURE_DECL: u32      = 0xFFFFFF20; // -224
pub const TEXTURE_CONT: u32      = 0xFFFFFF21; // -223
pub const TEXTURE_INFO: u32      = 0xFFFFFF22; // -222
pub const SHADER_LIT_TEXTURE_V0: u32 = 0xFFFFFF30; // -208
pub const SHADER_PAINTER_V0: u32 = 0xFFFFFF31; // -207
pub const SHADER_PAINTER: u32    = 0xFFFFFF32; // -206
pub const SHADER_ENGRAVER: u32   = 0xFFFFFF33; // -205
pub const SHADER_NEWSPRINT: u32  = 0xFFFFFF34; // -204
pub const SHADER_PARTICLE: u32   = 0xFFFFFF35; // -203
pub const SHADER_LIT_TEXTURE_V1: u32 = 0xFFFFFF36; // -202
pub const SHADER_INKER: u32      = 0xFFFFFF37; // -201
pub const SHADER_LIT_TEXTURE: u32 = 0xFFFFFF38; // -200
pub const MODEL_BLOCK2: u32      = 0xFFFFFF45; // -187
pub const COMP_SYNCH_TABLE: u32  = 0xFFFFFF47; // -185
pub const DISTAL_EDGE_MERGE: u32 = 0xFFFFFF48; // -184
pub const COMPRESSED_GEOM: u32   = 0xFFFFFF49; // -183
pub const BONES_BLOCK: u32       = 0xFFFFFF4B; // -181
pub const ORIG_TEX_COORDS: u32   = 0xFFFFFF4C; // -180
pub const TEX_COORDS: u32        = 0xFFFFFF4E; // -178
pub const LIGHT_RESOURCE: u32    = 0xFFFFFF50; // -176
pub const MOTION_BLOCK: u32      = 0xFFFFFF67; // -153
pub const GROUP_NODE_V1: u32     = 0xFFFFFF70; // -144
pub const LIGHT_NODE_V1: u32     = 0xFFFFFF71; // -143
pub const MODEL_NODE_V1: u32     = 0xFFFFFF72; // -142
pub const VIEW_NODE_V1: u32      = 0xFFFFFF74; // -140
pub const VIEW_NODE: u32         = 0xFFFFFF75; // -139
pub const LIGHT_NODE: u32        = 0xFFFFFF76; // -138
pub const GROUP_NODE: u32        = 0xFFFFFF77; // -137
pub const MODEL_NODE: u32        = 0xFFFFFF78; // -136
pub const RAW_MESH: u32          = 0xFFFFFF80; // -128
pub const PLANE: u32             = 0xFFFFFF81; // -127
pub const BOX: u32               = 0xFFFFFF82; // -126
pub const SPHERE: u32            = 0xFFFFFF83; // -125
pub const CYLINDER2: u32         = 0xFFFFFF84; // -124 (alternate)
pub const GLYPH_3D: u32          = 0xFFFFFF86; // -122
pub const PARTICLE_SYS: u32      = 0xFFFFFF87; // -121
pub const CYLINDER: u32          = 0xFFFFFF88; // -120
pub const PHYSICS_MESH: u32      = 0xFFFFFF89; // -119
pub const MODIFIER_PARAM_92: u32 = 0xFFFFFF92; // -110
pub const MODIFIER_PARAM_94: u32 = 0xFFFFFF94; // -108
pub const MODIFIER_PARAM_95: u32 = 0xFFFFFF95; // -107
pub const SKELETON_MODIFIER: u32 = 0xFFFFFF96; // -106
pub const MODIFIER_PARAM_97: u32 = 0xFFFFFF97; // -105
pub const UV_GENERATOR: u32      = 0xFFFFFFA0; // -96
pub const SUBDIV_SURFACE: u32    = 0xFFFFFFA1; // -95
pub const PHYSICS_MODIFIER: u32  = 0xFFFFFFA4; // -92
pub const DEFORM_MODIFIER: u32   = 0xFFFFFFA5; // -91
pub const INKER_MODIFIER: u32    = 0xFFFFFFA6; // -90

pub fn block_type_name(block_type: u32) -> &'static str {
    match block_type {
        IFX_HEADER => "IFX Header",
        CONTEXT_SEP => "Context Separator",
        FILE_HEADER => "File Header",
        MATERIAL_V1 => "Material (v1)",
        MATERIAL => "Material",
        TEXTURE_DECL => "Texture Declaration",
        TEXTURE_CONT => "Texture Continuation",
        TEXTURE_INFO => "Texture Info",
        SHADER_LIT_TEXTURE_V0 => "Shader LitTexture (v0)",
        SHADER_PAINTER_V0 => "Shader Painter (v0)",
        SHADER_PAINTER => "Shader Painter",
        SHADER_ENGRAVER => "Shader Engraver",
        SHADER_NEWSPRINT => "Shader Newsprint",
        SHADER_PARTICLE => "Shader Particle",
        SHADER_LIT_TEXTURE_V1 => "Shader LitTexture (v1)",
        SHADER_INKER => "Shader Inker",
        SHADER_LIT_TEXTURE => "Shader LitTexture",
        MODEL_BLOCK2 => "Model Resource",
        COMP_SYNCH_TABLE => "Compressed Synch Table",
        DISTAL_EDGE_MERGE => "Distal Edge Merge List",
        COMPRESSED_GEOM => "Compressed Geometry (CLOD)",
        BONES_BLOCK => "Bones/Skeleton",
        ORIG_TEX_COORDS => "Original Texture Coords",
        TEX_COORDS => "Texture Coords",
        LIGHT_RESOURCE => "Light Resource",
        MOTION_BLOCK => "Motion/Animation",
        GROUP_NODE_V1 => "Group Node (v1)",
        LIGHT_NODE_V1 => "Light Node (v1)",
        MODEL_NODE_V1 => "Model Node (v1)",
        VIEW_NODE_V1 => "View Node (v1)",
        VIEW_NODE => "View Node",
        LIGHT_NODE => "Light Node",
        GROUP_NODE => "Group Node",
        MODEL_NODE => "Model Node",
        RAW_MESH => "Raw Mesh",
        PLANE => "Plane Primitive",
        BOX => "Box Primitive",
        SPHERE => "Sphere Primitive",
        CYLINDER => "Cylinder Primitive",
        CYLINDER2 => "Cylinder Primitive (alt)",
        GLYPH_3D => "3D Glyph",
        PARTICLE_SYS => "Particle System",
        PHYSICS_MESH => "Physics Mesh",
        MODIFIER_PARAM_92 => "Modifier Param (-110)",
        MODIFIER_PARAM_94 => "MRM Modifier Param",
        MODIFIER_PARAM_95 => "Physics Modifier Param",
        SKELETON_MODIFIER => "Skeleton Modifier",
        MODIFIER_PARAM_97 => "Modifier Param (-105)",
        UV_GENERATOR => "UV Generator",
        SUBDIV_SURFACE => "Subdivision Surface",
        PHYSICS_MODIFIER => "Physics Modifier",
        DEFORM_MODIFIER => "Deform Modifier",
        INKER_MODIFIER => "Inker Modifier",
        _ => "Unknown",
    }
}
