// SPDX-License-Identifier: GPL-3.0-only
//
//! The C-ABI plugin authors must expose to the host.
//!
//! In the Component Model world this file is generated by `wit-bindgen`.
//! Until browsers grow native Component Model support, the equivalent
//! hand-rolled exports live here.
//!
//! ## What a plugin must export
//!
//! ```ignore
//! #[unsafe(no_mangle)]
//! pub extern "C" fn __plugin_alloc(size: u32) -> u32 { ... }
//!
//! #[unsafe(no_mangle)]
//! pub extern "C" fn __plugin_dealloc(ptr: u32, size: u32) { ... }
//!
//! #[unsafe(no_mangle)]
//! pub extern "C" fn __xtra_name() -> u64 { ... }
//!
//! #[unsafe(no_mangle)]
//! pub extern "C" fn __xtra_create_instance(args_ptr: u32, args_len: u32) -> u64 { ... }
//!
//! #[unsafe(no_mangle)]
//! pub extern "C" fn __xtra_destroy_instance(id: u32) { ... }
//!
//! #[unsafe(no_mangle)]
//! pub extern "C" fn __xtra_call_handler(
//!     id: u32, name_ptr: u32, name_len: u32, args_ptr: u32, args_len: u32,
//! ) -> u64 { ... }
//!
//! #[unsafe(no_mangle)]
//! pub extern "C" fn __xtra_has_static_handler(name_ptr: u32, name_len: u32) -> u32 { ... }
//!
//! #[unsafe(no_mangle)]
//! pub extern "C" fn __xtra_call_static_handler(
//!     name_ptr: u32, name_len: u32, args_ptr: u32, args_len: u32,
//! ) -> u64 { ... }
//!
//! #[unsafe(no_mangle)]
//! pub extern "C" fn __xtra_has_async_handler(name_ptr: u32, name_len: u32) -> u32 { ... }
//! ```
//!
//! The `#[xtra_plugin]` proc macro generates all of these from the user's
//! `XtraPlugin` impl. Phase 1 plugin authors writing by hand can call the
//! `dispatch_*` helper functions below to do the heavy lifting, leaving
//! the actual `extern "C"` boilerplate as a short adapter.

use alloc::{string::String, vec::Vec};
use core::mem;

use crate::datum::Datum;
use crate::plugin::{XtraInstance, XtraPlugin};
use crate::wire;

// ── Buffer allocation surface the host calls into ────────────────────────

/// Default `__plugin_alloc` impl backing this SDK. Plugin authors who
/// don't override it get this for free via the `provide_plugin_alloc!()`
/// macro that the `#[xtra_plugin]` proc macro emits. Phase 1 plugins
/// must export it manually — see the module-level docs.
///
/// Returns the pointer (within the plugin's linear memory) of a buffer
/// at least `size` bytes long. The host writes its output there and
/// returns the same pointer back through whichever dx_* extern. The
/// plugin reclaims the buffer with [`plugin_take_buffer`].
pub fn plugin_alloc(size: u32) -> u32 {
    let mut buf: Vec<u8> = Vec::with_capacity(size as usize);
    // Make the Vec's logical length match capacity so the leaked
    // pointer is consistent with what `Vec::from_raw_parts` expects
    // when the plugin later reclaims it.
    unsafe { buf.set_len(size as usize) };
    let ptr = buf.as_mut_ptr() as u32;
    mem::forget(buf);
    ptr
}

/// Default `__plugin_dealloc` impl. Reclaims a buffer the host allocated
/// in this plugin via `plugin_alloc` but never actually returned through
/// the wire (e.g. when an extern call failed before transferring
/// ownership). In the normal flow the wire helpers already drop the
/// reclaimed `Vec<u8>`, which dealloc's automatically — this entry point
/// is for the failure path.
pub fn plugin_dealloc(ptr: u32, size: u32) {
    if ptr == 0 || size == 0 {
        return;
    }
    unsafe {
        let _ = Vec::from_raw_parts(ptr as *mut u8, size as usize, size as usize);
    }
}

// ── Dispatch helpers plugin authors compose into their exports ───────────

/// Pack a `(ptr, len)` pair into the `u64` shape the externs use.
#[inline]
pub fn pack(ptr: u32, len: u32) -> u64 {
    ((ptr as u64) << 32) | (len as u64)
}

/// Allocate plugin-side memory and copy `bytes` into it. Returns the
/// packed `(ptr, len)` u64 to hand back to the host.
pub fn return_bytes(bytes: &[u8]) -> u64 {
    if bytes.is_empty() {
        return 0;
    }
    let ptr = plugin_alloc(bytes.len() as u32);
    unsafe {
        core::ptr::copy_nonoverlapping(bytes.as_ptr(), ptr as *mut u8, bytes.len());
    }
    pack(ptr, bytes.len() as u32)
}

/// Plugin-side: turn a `(ptr, len)` host argument back into a borrowed
/// `&[u8]` slice for decoding. The slice is valid for the duration of
/// the call — the host MUST NOT retain it.
///
/// # Safety
/// `ptr` and `len` come straight from the host; the caller must trust
/// the host to pass a valid range. Mis-routed inputs will return garbage,
/// not crash, since WASM bounds-checks all memory access.
#[inline]
pub unsafe fn input_slice<'a>(ptr: u32, len: u32) -> &'a [u8] {
    if ptr == 0 || len == 0 {
        return &[];
    }
    unsafe { core::slice::from_raw_parts(ptr as *const u8, len as usize) }
}

/// Decode an `Args` wire frame from `(ptr, len)`. Returns `Err` on
/// malformed input; plugin authors typically map the error into
/// `WireFrame::Error` via [`encode_error`].
pub fn decode_args(ptr: u32, len: u32) -> Result<Vec<Datum>, String> {
    let bytes = unsafe { input_slice(ptr, len) };
    wire::decode_args(bytes)
}

/// Compose a result `Datum` into a host-bound return value (allocated
/// in plugin memory). The host reads the bytes and dealloc's the buffer
/// via `__plugin_dealloc`.
pub fn return_datum(value: &Datum) -> u64 {
    let bytes = wire::encode_return(value);
    return_bytes(&bytes)
}

/// Compose a result error into a host-bound return value.
pub fn return_error(msg: &str) -> u64 {
    let bytes = wire::encode_error(msg);
    return_bytes(&bytes)
}

/// Compose a Result<Datum, String> into the wire-level return.
pub fn return_result(result: Result<Datum, String>) -> u64 {
    match result {
        Ok(v) => return_datum(&v),
        Err(e) => return_error(&e),
    }
}

// ── Static handler dispatch ──────────────────────────────────────────────
//
// Static handlers don't need an instance registry — they call directly
// into `P::call_static_handler`. The helpers below let plugins keep
// their `extern "C"` body to a single line.

/// Plugin-side helper for `__xtra_has_static_handler`. Decodes the name,
/// lowercases it, and queries the plugin.
pub fn dispatch_has_static_handler<P: XtraPlugin>(name_ptr: u32, name_len: u32) -> u32 {
    let name_bytes = unsafe { input_slice(name_ptr, name_len) };
    let Ok(name) = core::str::from_utf8(name_bytes) else {
        return 0;
    };
    if P::has_static_handler(&name.to_lowercase()) { 1 } else { 0 }
}

/// Plugin-side helper for `__xtra_has_async_handler`.
pub fn dispatch_has_async_handler<P: XtraPlugin>(name_ptr: u32, name_len: u32) -> u32 {
    let name_bytes = unsafe { input_slice(name_ptr, name_len) };
    let Ok(name) = core::str::from_utf8(name_bytes) else {
        return 0;
    };
    if P::has_async_handler(&name.to_lowercase()) { 1 } else { 0 }
}

/// Plugin-side helper for `__xtra_call_static_handler`.
pub fn dispatch_call_static_handler<P: XtraPlugin>(
    name_ptr: u32,
    name_len: u32,
    args_ptr: u32,
    args_len: u32,
) -> u64 {
    let name_bytes = unsafe { input_slice(name_ptr, name_len) };
    let name = match core::str::from_utf8(name_bytes) {
        Ok(s) => s.to_lowercase(),
        Err(_) => return return_error("__xtra_call_static_handler: name is not UTF-8"),
    };
    let args = match decode_args(args_ptr, args_len) {
        Ok(a) => a,
        Err(e) => return return_error(&e),
    };
    return_result(P::call_static_handler(&name, &args))
}

// ── Instance-handler dispatch & registry ─────────────────────────────────

/// Instance registry used by a single plugin module. Plugin authors
/// (or the `#[xtra_plugin]` macro) declare one `static mut` of this
/// type and route the `__xtra_*` exports through it.
///
/// Single-threaded WASM means `unsafe { &mut REGISTRY }` is sound as
/// long as plugin authors don't recursively re-enter the registry from
/// inside a handler call.
pub struct InstanceRegistry<I: XtraInstance> {
    next_id: u32,
    entries: Vec<Option<I>>,
}

impl<I: XtraInstance> InstanceRegistry<I> {
    pub const fn new() -> Self {
        Self {
            next_id: 1,
            entries: Vec::new(),
        }
    }

    /// Insert a new instance and return its id. Reuses freed slots
    /// when available; otherwise grows the vector.
    pub fn insert(&mut self, instance: I) -> u32 {
        // Try to reuse a freed slot first to keep ids stable and small.
        for (i, slot) in self.entries.iter_mut().enumerate() {
            if slot.is_none() {
                *slot = Some(instance);
                return (i as u32) + 1;
            }
        }
        let id = self.next_id;
        self.next_id = self.next_id.checked_add(1).unwrap_or(u32::MAX);
        self.entries.push(Some(instance));
        id
    }

    pub fn get_mut(&mut self, id: u32) -> Option<&mut I> {
        if id == 0 {
            return None;
        }
        self.entries.get_mut((id - 1) as usize)?.as_mut()
    }

    pub fn remove(&mut self, id: u32) -> Option<I> {
        if id == 0 {
            return None;
        }
        self.entries.get_mut((id - 1) as usize)?.take()
    }
}

/// Dispatch helper for `__xtra_create_instance`. Decodes args, calls
/// `P::create_instance`, inserts into the supplied registry, returns
/// an `Int(instance_id)` wire frame (or an error frame).
pub fn dispatch_create_instance<P: XtraPlugin>(
    args_ptr: u32,
    args_len: u32,
    registry: &mut InstanceRegistry<P::Instance>,
) -> u64 {
    let args = match decode_args(args_ptr, args_len) {
        Ok(a) => a,
        Err(e) => return return_error(&e),
    };
    match P::create_instance(&args) {
        Ok(inst) => {
            let id = registry.insert(inst);
            return_datum(&Datum::Int(id as i32))
        }
        Err(e) => return_error(&e),
    }
}

/// Dispatch helper for `__xtra_destroy_instance`.
pub fn dispatch_destroy_instance<P: XtraPlugin>(
    id: u32,
    registry: &mut InstanceRegistry<P::Instance>,
) {
    if let Some(mut inst) = registry.remove(id) {
        inst.destroy();
    }
}

/// Dispatch helper for `__xtra_call_handler`.
pub fn dispatch_call_handler<P: XtraPlugin>(
    id: u32,
    name_ptr: u32,
    name_len: u32,
    args_ptr: u32,
    args_len: u32,
    registry: &mut InstanceRegistry<P::Instance>,
) -> u64 {
    let name_bytes = unsafe { input_slice(name_ptr, name_len) };
    let name = match core::str::from_utf8(name_bytes) {
        Ok(s) => s.to_lowercase(),
        Err(_) => return return_error("__xtra_call_handler: name is not UTF-8"),
    };
    let args = match decode_args(args_ptr, args_len) {
        Ok(a) => a,
        Err(e) => return return_error(&e),
    };
    let Some(inst) = registry.get_mut(id) else {
        return return_error(&alloc::format!(
            "{}: no instance with id {}",
            P::xtra_name(),
            id
        ));
    };
    return_result(inst.call_handler(&name, &args))
}

/// Dispatch helper for `__xtra_name`. Allocates plugin memory, copies
/// the xtra name into it, returns the packed `(ptr, len)`.
pub fn dispatch_xtra_name<P: XtraPlugin>() -> u64 {
    return_bytes(P::xtra_name().as_bytes())
}
